import type { Category } from "@/lib/category-context";
import type { ArtStyle } from "@shared/schema";

// Auto-generated by scripts/regenerate-gallery.ts

import pets_oil_painting_1 from "@/assets/generated_gallery/pets-oil-painting-1.png";
import pets_oil_painting_2 from "@/assets/generated_gallery/pets-oil-painting-2.png";
import pets_oil_painting_3 from "@/assets/generated_gallery/pets-oil-painting-3.png";
import pets_acrylic_1 from "@/assets/generated_gallery/pets-acrylic-1.png";
import pets_acrylic_2 from "@/assets/generated_gallery/pets-acrylic-2.png";
import pets_acrylic_3 from "@/assets/generated_gallery/pets-acrylic-3.png";
import pets_pencil_sketch_1 from "@/assets/generated_gallery/pets-pencil-sketch-1.png";
import pets_pencil_sketch_2 from "@/assets/generated_gallery/pets-pencil-sketch-2.png";
import pets_pencil_sketch_3 from "@/assets/generated_gallery/pets-pencil-sketch-3.png";
import pets_watercolor_1 from "@/assets/generated_gallery/pets-watercolor-1.png";
import pets_watercolor_2 from "@/assets/generated_gallery/pets-watercolor-2.png";
import pets_watercolor_3 from "@/assets/generated_gallery/pets-watercolor-3.png";
import pets_charcoal_1 from "@/assets/generated_gallery/pets-charcoal-1.png";
import pets_charcoal_2 from "@/assets/generated_gallery/pets-charcoal-2.png";
import pets_charcoal_3 from "@/assets/generated_gallery/pets-charcoal-3.png";
import pets_pastel_1 from "@/assets/generated_gallery/pets-pastel-1.png";
import pets_pastel_2 from "@/assets/generated_gallery/pets-pastel-2.png";
import pets_pastel_3 from "@/assets/generated_gallery/pets-pastel-3.png";
import family_oil_painting_1 from "@/assets/generated_gallery/family-oil-painting-1.png";
import family_oil_painting_2 from "@/assets/generated_gallery/family-oil-painting-2.png";
import family_oil_painting_3 from "@/assets/generated_gallery/family-oil-painting-3.png";
import family_acrylic_1 from "@/assets/generated_gallery/family-acrylic-1.png";
import family_acrylic_2 from "@/assets/generated_gallery/family-acrylic-2.png";
import family_acrylic_3 from "@/assets/generated_gallery/family-acrylic-3.png";
import family_pencil_sketch_1 from "@/assets/generated_gallery/family-pencil-sketch-1.png";
import family_pencil_sketch_2 from "@/assets/generated_gallery/family-pencil-sketch-2.png";
import family_pencil_sketch_3 from "@/assets/generated_gallery/family-pencil-sketch-3.png";
import family_watercolor_1 from "@/assets/generated_gallery/family-watercolor-1.png";
import family_watercolor_2 from "@/assets/generated_gallery/family-watercolor-2.png";
import family_watercolor_3 from "@/assets/generated_gallery/family-watercolor-3.png";
import family_charcoal_1 from "@/assets/generated_gallery/family-charcoal-1.png";
import family_charcoal_2 from "@/assets/generated_gallery/family-charcoal-2.png";
import family_charcoal_3 from "@/assets/generated_gallery/family-charcoal-3.png";
import family_pastel_1 from "@/assets/generated_gallery/family-pastel-1.png";
import family_pastel_2 from "@/assets/generated_gallery/family-pastel-2.png";
import family_pastel_3 from "@/assets/generated_gallery/family-pastel-3.png";
import kids_oil_painting_1 from "@/assets/generated_gallery/kids-oil-painting-1.png";
import kids_oil_painting_2 from "@/assets/generated_gallery/kids-oil-painting-2.png";
import kids_oil_painting_3 from "@/assets/generated_gallery/kids-oil-painting-3.png";
import kids_acrylic_1 from "@/assets/generated_gallery/kids-acrylic-1.png";
import kids_acrylic_2 from "@/assets/generated_gallery/kids-acrylic-2.png";
import kids_acrylic_3 from "@/assets/generated_gallery/kids-acrylic-3.png";
import kids_pencil_sketch_1 from "@/assets/generated_gallery/kids-pencil-sketch-1.png";
import kids_pencil_sketch_2 from "@/assets/generated_gallery/kids-pencil-sketch-2.png";
import kids_pencil_sketch_3 from "@/assets/generated_gallery/kids-pencil-sketch-3.png";
import kids_watercolor_1 from "@/assets/generated_gallery/kids-watercolor-1.png";
import kids_watercolor_2 from "@/assets/generated_gallery/kids-watercolor-2.png";
import kids_watercolor_3 from "@/assets/generated_gallery/kids-watercolor-3.png";
import kids_charcoal_1 from "@/assets/generated_gallery/kids-charcoal-1.png";
import kids_charcoal_2 from "@/assets/generated_gallery/kids-charcoal-2.png";
import kids_charcoal_3 from "@/assets/generated_gallery/kids-charcoal-3.png";
import kids_pastel_1 from "@/assets/generated_gallery/kids-pastel-1.png";
import kids_pastel_2 from "@/assets/generated_gallery/kids-pastel-2.png";
import kids_pastel_3 from "@/assets/generated_gallery/kids-pastel-3.png";
import couples_oil_painting_1 from "@/assets/generated_gallery/couples-oil-painting-1.png";
import couples_oil_painting_2 from "@/assets/generated_gallery/couples-oil-painting-2.png";
import couples_oil_painting_3 from "@/assets/generated_gallery/couples-oil-painting-3.png";
import couples_acrylic_1 from "@/assets/generated_gallery/couples-acrylic-1.png";
import couples_acrylic_2 from "@/assets/generated_gallery/couples-acrylic-2.png";
import couples_acrylic_3 from "@/assets/generated_gallery/couples-acrylic-3.png";
import couples_pencil_sketch_1 from "@/assets/generated_gallery/couples-pencil-sketch-1.png";
import couples_pencil_sketch_2 from "@/assets/generated_gallery/couples-pencil-sketch-2.png";
import couples_pencil_sketch_3 from "@/assets/generated_gallery/couples-pencil-sketch-3.png";
import couples_watercolor_1 from "@/assets/generated_gallery/couples-watercolor-1.png";
import couples_watercolor_2 from "@/assets/generated_gallery/couples-watercolor-2.png";
import couples_watercolor_3 from "@/assets/generated_gallery/couples-watercolor-3.png";
import couples_charcoal_1 from "@/assets/generated_gallery/couples-charcoal-1.png";
import couples_charcoal_2 from "@/assets/generated_gallery/couples-charcoal-2.png";
import couples_charcoal_3 from "@/assets/generated_gallery/couples-charcoal-3.png";
import couples_pastel_1 from "@/assets/generated_gallery/couples-pastel-1.png";
import couples_pastel_2 from "@/assets/generated_gallery/couples-pastel-2.png";
import couples_pastel_3 from "@/assets/generated_gallery/couples-pastel-3.png";
import self_portrait_oil_painting_1 from "@/assets/generated_gallery/self-portrait-oil-painting-1.png";
import self_portrait_oil_painting_2 from "@/assets/generated_gallery/self-portrait-oil-painting-2.png";
import self_portrait_oil_painting_3 from "@/assets/generated_gallery/self-portrait-oil-painting-3.png";
import self_portrait_acrylic_1 from "@/assets/generated_gallery/self-portrait-acrylic-1.png";
import self_portrait_acrylic_2 from "@/assets/generated_gallery/self-portrait-acrylic-2.png";
import self_portrait_acrylic_3 from "@/assets/generated_gallery/self-portrait-acrylic-3.png";
import self_portrait_pencil_sketch_1 from "@/assets/generated_gallery/self-portrait-pencil-sketch-1.png";
import self_portrait_pencil_sketch_2 from "@/assets/generated_gallery/self-portrait-pencil-sketch-2.png";
import self_portrait_pencil_sketch_3 from "@/assets/generated_gallery/self-portrait-pencil-sketch-3.png";
import self_portrait_watercolor_1 from "@/assets/generated_gallery/self-portrait-watercolor-1.png";
import self_portrait_watercolor_2 from "@/assets/generated_gallery/self-portrait-watercolor-2.png";
import self_portrait_watercolor_3 from "@/assets/generated_gallery/self-portrait-watercolor-3.png";
import self_portrait_charcoal_1 from "@/assets/generated_gallery/self-portrait-charcoal-1.png";
import self_portrait_charcoal_2 from "@/assets/generated_gallery/self-portrait-charcoal-2.png";
import self_portrait_charcoal_3 from "@/assets/generated_gallery/self-portrait-charcoal-3.png";
import self_portrait_pastel_1 from "@/assets/generated_gallery/self-portrait-pastel-1.png";
import self_portrait_pastel_2 from "@/assets/generated_gallery/self-portrait-pastel-2.png";
import self_portrait_pastel_3 from "@/assets/generated_gallery/self-portrait-pastel-3.png";

export const galleryImages: Record<Category, Record<ArtStyle, [string, string, string]>> = {
  "pets": {
    "oil-painting": [pets_oil_painting_1, pets_oil_painting_2, pets_oil_painting_3],
    "acrylic": [pets_acrylic_1, pets_acrylic_2, pets_acrylic_3],
    "pencil-sketch": [pets_pencil_sketch_1, pets_pencil_sketch_2, pets_pencil_sketch_3],
    "watercolor": [pets_watercolor_1, pets_watercolor_2, pets_watercolor_3],
    "charcoal": [pets_charcoal_1, pets_charcoal_2, pets_charcoal_3],
    "pastel": [pets_pastel_1, pets_pastel_2, pets_pastel_3],
  },
  "family": {
    "oil-painting": [family_oil_painting_1, family_oil_painting_2, family_oil_painting_3],
    "acrylic": [family_acrylic_1, family_acrylic_2, family_acrylic_3],
    "pencil-sketch": [family_pencil_sketch_1, family_pencil_sketch_2, family_pencil_sketch_3],
    "watercolor": [family_watercolor_1, family_watercolor_2, family_watercolor_3],
    "charcoal": [family_charcoal_1, family_charcoal_2, family_charcoal_3],
    "pastel": [family_pastel_1, family_pastel_2, family_pastel_3],
  },
  "kids": {
    "oil-painting": [kids_oil_painting_1, kids_oil_painting_2, kids_oil_painting_3],
    "acrylic": [kids_acrylic_1, kids_acrylic_2, kids_acrylic_3],
    "pencil-sketch": [kids_pencil_sketch_1, kids_pencil_sketch_2, kids_pencil_sketch_3],
    "watercolor": [kids_watercolor_1, kids_watercolor_2, kids_watercolor_3],
    "charcoal": [kids_charcoal_1, kids_charcoal_2, kids_charcoal_3],
    "pastel": [kids_pastel_1, kids_pastel_2, kids_pastel_3],
  },
  "couples": {
    "oil-painting": [couples_oil_painting_1, couples_oil_painting_2, couples_oil_painting_3],
    "acrylic": [couples_acrylic_1, couples_acrylic_2, couples_acrylic_3],
    "pencil-sketch": [couples_pencil_sketch_1, couples_pencil_sketch_2, couples_pencil_sketch_3],
    "watercolor": [couples_watercolor_1, couples_watercolor_2, couples_watercolor_3],
    "charcoal": [couples_charcoal_1, couples_charcoal_2, couples_charcoal_3],
    "pastel": [couples_pastel_1, couples_pastel_2, couples_pastel_3],
  },
  "self-portrait": {
    "oil-painting": [self_portrait_oil_painting_1, self_portrait_oil_painting_2, self_portrait_oil_painting_3],
    "acrylic": [self_portrait_acrylic_1, self_portrait_acrylic_2, self_portrait_acrylic_3],
    "pencil-sketch": [self_portrait_pencil_sketch_1, self_portrait_pencil_sketch_2, self_portrait_pencil_sketch_3],
    "watercolor": [self_portrait_watercolor_1, self_portrait_watercolor_2, self_portrait_watercolor_3],
    "charcoal": [self_portrait_charcoal_1, self_portrait_charcoal_2, self_portrait_charcoal_3],
    "pastel": [self_portrait_pastel_1, self_portrait_pastel_2, self_portrait_pastel_3],
  },
};