/**
 * Mood-specific gallery preview images. Auto-generated by scripts/generate-mood-gallery-ts.ts
 * Do not edit by hand.
 */
import type { Category } from "@/lib/category-context";
import type { ArtStyle } from "@shared/schema";

import royal_noble_pets_oil_painting_1 from "@/assets/mood/royal_noble--pets-oil-painting-1.png";
import royal_noble_pets_oil_painting_2 from "@/assets/mood/royal_noble--pets-oil-painting-2.png";
import royal_noble_pets_oil_painting_3 from "@/assets/mood/royal_noble--pets-oil-painting-3.png";
import royal_noble_pets_acrylic_1 from "@/assets/mood/royal_noble--pets-acrylic-1.png";
import royal_noble_pets_acrylic_2 from "@/assets/mood/royal_noble--pets-acrylic-2.png";
import royal_noble_pets_acrylic_3 from "@/assets/mood/royal_noble--pets-acrylic-3.png";
import royal_noble_pets_pencil_sketch_1 from "@/assets/mood/royal_noble--pets-pencil-sketch-1.png";
import royal_noble_pets_pencil_sketch_2 from "@/assets/mood/royal_noble--pets-pencil-sketch-2.png";
import royal_noble_pets_pencil_sketch_3 from "@/assets/mood/royal_noble--pets-pencil-sketch-3.png";
import royal_noble_pets_watercolor_1 from "@/assets/mood/royal_noble--pets-watercolor-1.png";
import royal_noble_pets_watercolor_2 from "@/assets/mood/royal_noble--pets-watercolor-2.png";
import royal_noble_pets_watercolor_3 from "@/assets/mood/royal_noble--pets-watercolor-3.png";
import royal_noble_pets_charcoal_1 from "@/assets/mood/royal_noble--pets-charcoal-1.png";
import royal_noble_pets_charcoal_2 from "@/assets/mood/royal_noble--pets-charcoal-2.png";
import royal_noble_pets_charcoal_3 from "@/assets/mood/royal_noble--pets-charcoal-3.png";
import royal_noble_pets_pastel_1 from "@/assets/mood/royal_noble--pets-pastel-1.png";
import royal_noble_pets_pastel_2 from "@/assets/mood/royal_noble--pets-pastel-2.png";
import royal_noble_pets_pastel_3 from "@/assets/mood/royal_noble--pets-pastel-3.png";
import royal_noble_family_oil_painting_1 from "@/assets/mood/royal_noble--family-oil-painting-1.png";
import royal_noble_family_oil_painting_2 from "@/assets/mood/royal_noble--family-oil-painting-2.png";
import royal_noble_family_oil_painting_3 from "@/assets/mood/royal_noble--family-oil-painting-3.png";
import royal_noble_family_acrylic_1 from "@/assets/mood/royal_noble--family-acrylic-1.png";
import royal_noble_family_acrylic_2 from "@/assets/mood/royal_noble--family-acrylic-2.png";
import royal_noble_family_acrylic_3 from "@/assets/mood/royal_noble--family-acrylic-3.png";
import royal_noble_family_pencil_sketch_1 from "@/assets/mood/royal_noble--family-pencil-sketch-1.png";
import royal_noble_family_pencil_sketch_2 from "@/assets/mood/royal_noble--family-pencil-sketch-2.png";
import royal_noble_family_pencil_sketch_3 from "@/assets/mood/royal_noble--family-pencil-sketch-3.png";
import royal_noble_family_watercolor_1 from "@/assets/mood/royal_noble--family-watercolor-1.png";
import royal_noble_family_watercolor_2 from "@/assets/mood/royal_noble--family-watercolor-2.png";
import royal_noble_family_watercolor_3 from "@/assets/mood/royal_noble--family-watercolor-3.png";
import royal_noble_family_charcoal_1 from "@/assets/mood/royal_noble--family-charcoal-1.png";
import royal_noble_family_charcoal_2 from "@/assets/mood/royal_noble--family-charcoal-2.png";
import royal_noble_family_charcoal_3 from "@/assets/mood/royal_noble--family-charcoal-3.png";
import royal_noble_family_pastel_1 from "@/assets/mood/royal_noble--family-pastel-1.png";
import royal_noble_family_pastel_2 from "@/assets/mood/royal_noble--family-pastel-2.png";
import royal_noble_family_pastel_3 from "@/assets/mood/royal_noble--family-pastel-3.png";
import royal_noble_kids_oil_painting_1 from "@/assets/mood/royal_noble--kids-oil-painting-1.png";
import royal_noble_kids_oil_painting_2 from "@/assets/mood/royal_noble--kids-oil-painting-2.png";
import royal_noble_kids_oil_painting_3 from "@/assets/mood/royal_noble--kids-oil-painting-3.png";
import royal_noble_kids_acrylic_1 from "@/assets/mood/royal_noble--kids-acrylic-1.png";
import royal_noble_kids_acrylic_2 from "@/assets/mood/royal_noble--kids-acrylic-2.png";
import royal_noble_kids_acrylic_3 from "@/assets/mood/royal_noble--kids-acrylic-3.png";
import royal_noble_kids_pencil_sketch_1 from "@/assets/mood/royal_noble--kids-pencil-sketch-1.png";
import royal_noble_kids_pencil_sketch_2 from "@/assets/mood/royal_noble--kids-pencil-sketch-2.png";
import royal_noble_kids_pencil_sketch_3 from "@/assets/mood/royal_noble--kids-pencil-sketch-3.png";
import royal_noble_kids_watercolor_1 from "@/assets/mood/royal_noble--kids-watercolor-1.png";
import royal_noble_kids_watercolor_2 from "@/assets/mood/royal_noble--kids-watercolor-2.png";
import royal_noble_kids_watercolor_3 from "@/assets/mood/royal_noble--kids-watercolor-3.png";
import royal_noble_kids_charcoal_1 from "@/assets/mood/royal_noble--kids-charcoal-1.png";
import royal_noble_kids_charcoal_2 from "@/assets/mood/royal_noble--kids-charcoal-2.png";
import royal_noble_kids_charcoal_3 from "@/assets/mood/royal_noble--kids-charcoal-3.png";
import royal_noble_kids_pastel_1 from "@/assets/mood/royal_noble--kids-pastel-1.png";
import royal_noble_kids_pastel_2 from "@/assets/mood/royal_noble--kids-pastel-2.png";
import royal_noble_kids_pastel_3 from "@/assets/mood/royal_noble--kids-pastel-3.png";
import royal_noble_couples_oil_painting_1 from "@/assets/mood/royal_noble--couples-oil-painting-1.png";
import royal_noble_couples_oil_painting_2 from "@/assets/mood/royal_noble--couples-oil-painting-2.png";
import royal_noble_couples_oil_painting_3 from "@/assets/mood/royal_noble--couples-oil-painting-3.png";
import royal_noble_couples_acrylic_1 from "@/assets/mood/royal_noble--couples-acrylic-1.png";
import royal_noble_couples_acrylic_2 from "@/assets/mood/royal_noble--couples-acrylic-2.png";
import royal_noble_couples_acrylic_3 from "@/assets/mood/royal_noble--couples-acrylic-3.png";
import royal_noble_couples_pencil_sketch_1 from "@/assets/mood/royal_noble--couples-pencil-sketch-1.png";
import royal_noble_couples_pencil_sketch_2 from "@/assets/mood/royal_noble--couples-pencil-sketch-2.png";
import royal_noble_couples_pencil_sketch_3 from "@/assets/mood/royal_noble--couples-pencil-sketch-3.png";
import royal_noble_couples_watercolor_1 from "@/assets/mood/royal_noble--couples-watercolor-1.png";
import royal_noble_couples_watercolor_2 from "@/assets/mood/royal_noble--couples-watercolor-2.png";
import royal_noble_couples_watercolor_3 from "@/assets/mood/royal_noble--couples-watercolor-3.png";
import royal_noble_couples_charcoal_1 from "@/assets/mood/royal_noble--couples-charcoal-1.png";
import royal_noble_couples_charcoal_2 from "@/assets/mood/royal_noble--couples-charcoal-2.png";
import royal_noble_couples_charcoal_3 from "@/assets/mood/royal_noble--couples-charcoal-3.png";
import royal_noble_couples_pastel_1 from "@/assets/mood/royal_noble--couples-pastel-1.png";
import royal_noble_couples_pastel_2 from "@/assets/mood/royal_noble--couples-pastel-2.png";
import royal_noble_couples_pastel_3 from "@/assets/mood/royal_noble--couples-pastel-3.png";
import royal_noble_self_portrait_oil_painting_1 from "@/assets/mood/royal_noble--self-portrait-oil-painting-1.png";
import royal_noble_self_portrait_oil_painting_2 from "@/assets/mood/royal_noble--self-portrait-oil-painting-2.png";
import royal_noble_self_portrait_oil_painting_3 from "@/assets/mood/royal_noble--self-portrait-oil-painting-3.png";
import royal_noble_self_portrait_acrylic_1 from "@/assets/mood/royal_noble--self-portrait-acrylic-1.png";
import royal_noble_self_portrait_acrylic_2 from "@/assets/mood/royal_noble--self-portrait-acrylic-2.png";
import royal_noble_self_portrait_acrylic_3 from "@/assets/mood/royal_noble--self-portrait-acrylic-3.png";
import royal_noble_self_portrait_pencil_sketch_1 from "@/assets/mood/royal_noble--self-portrait-pencil-sketch-1.png";
import royal_noble_self_portrait_pencil_sketch_2 from "@/assets/mood/royal_noble--self-portrait-pencil-sketch-2.png";
import royal_noble_self_portrait_pencil_sketch_3 from "@/assets/mood/royal_noble--self-portrait-pencil-sketch-3.png";
import royal_noble_self_portrait_watercolor_1 from "@/assets/mood/royal_noble--self-portrait-watercolor-1.png";
import royal_noble_self_portrait_watercolor_2 from "@/assets/mood/royal_noble--self-portrait-watercolor-2.png";
import royal_noble_self_portrait_watercolor_3 from "@/assets/mood/royal_noble--self-portrait-watercolor-3.png";
import royal_noble_self_portrait_charcoal_1 from "@/assets/mood/royal_noble--self-portrait-charcoal-1.png";
import royal_noble_self_portrait_charcoal_2 from "@/assets/mood/royal_noble--self-portrait-charcoal-2.png";
import royal_noble_self_portrait_charcoal_3 from "@/assets/mood/royal_noble--self-portrait-charcoal-3.png";
import royal_noble_self_portrait_pastel_1 from "@/assets/mood/royal_noble--self-portrait-pastel-1.png";
import royal_noble_self_portrait_pastel_2 from "@/assets/mood/royal_noble--self-portrait-pastel-2.png";
import royal_noble_self_portrait_pastel_3 from "@/assets/mood/royal_noble--self-portrait-pastel-3.png";
import neoclassical_pets_oil_painting_1 from "@/assets/mood/neoclassical--pets-oil-painting-1.png";
import neoclassical_pets_oil_painting_2 from "@/assets/mood/neoclassical--pets-oil-painting-2.png";
import neoclassical_pets_oil_painting_3 from "@/assets/mood/neoclassical--pets-oil-painting-3.png";
import neoclassical_pets_acrylic_1 from "@/assets/mood/neoclassical--pets-acrylic-1.png";
import neoclassical_pets_acrylic_2 from "@/assets/mood/neoclassical--pets-acrylic-2.png";
import neoclassical_pets_acrylic_3 from "@/assets/mood/neoclassical--pets-acrylic-3.png";
import neoclassical_pets_pencil_sketch_1 from "@/assets/mood/neoclassical--pets-pencil-sketch-1.png";
import neoclassical_pets_pencil_sketch_2 from "@/assets/mood/neoclassical--pets-pencil-sketch-2.png";
import neoclassical_pets_pencil_sketch_3 from "@/assets/mood/neoclassical--pets-pencil-sketch-3.png";
import neoclassical_pets_watercolor_1 from "@/assets/mood/neoclassical--pets-watercolor-1.png";
import neoclassical_pets_watercolor_2 from "@/assets/mood/neoclassical--pets-watercolor-2.png";
import neoclassical_pets_watercolor_3 from "@/assets/mood/neoclassical--pets-watercolor-3.png";
import neoclassical_pets_charcoal_1 from "@/assets/mood/neoclassical--pets-charcoal-1.png";
import neoclassical_pets_charcoal_2 from "@/assets/mood/neoclassical--pets-charcoal-2.png";
import neoclassical_pets_charcoal_3 from "@/assets/mood/neoclassical--pets-charcoal-3.png";
import neoclassical_pets_pastel_1 from "@/assets/mood/neoclassical--pets-pastel-1.png";
import neoclassical_pets_pastel_2 from "@/assets/mood/neoclassical--pets-pastel-2.png";
import neoclassical_pets_pastel_3 from "@/assets/mood/neoclassical--pets-pastel-3.png";
import neoclassical_family_oil_painting_1 from "@/assets/mood/neoclassical--family-oil-painting-1.png";
import neoclassical_family_oil_painting_2 from "@/assets/mood/neoclassical--family-oil-painting-2.png";
import neoclassical_family_oil_painting_3 from "@/assets/mood/neoclassical--family-oil-painting-3.png";
import neoclassical_family_acrylic_1 from "@/assets/mood/neoclassical--family-acrylic-1.png";
import neoclassical_family_acrylic_2 from "@/assets/mood/neoclassical--family-acrylic-2.png";
import neoclassical_family_acrylic_3 from "@/assets/mood/neoclassical--family-acrylic-3.png";
import neoclassical_family_pencil_sketch_1 from "@/assets/mood/neoclassical--family-pencil-sketch-1.png";
import neoclassical_family_pencil_sketch_2 from "@/assets/mood/neoclassical--family-pencil-sketch-2.png";
import neoclassical_family_pencil_sketch_3 from "@/assets/mood/neoclassical--family-pencil-sketch-3.png";
import neoclassical_family_watercolor_1 from "@/assets/mood/neoclassical--family-watercolor-1.png";
import neoclassical_family_watercolor_2 from "@/assets/mood/neoclassical--family-watercolor-2.png";
import neoclassical_family_watercolor_3 from "@/assets/mood/neoclassical--family-watercolor-3.png";
import neoclassical_family_charcoal_1 from "@/assets/mood/neoclassical--family-charcoal-1.png";
import neoclassical_family_charcoal_2 from "@/assets/mood/neoclassical--family-charcoal-2.png";
import neoclassical_family_charcoal_3 from "@/assets/mood/neoclassical--family-charcoal-3.png";
import neoclassical_family_pastel_1 from "@/assets/mood/neoclassical--family-pastel-1.png";
import neoclassical_family_pastel_2 from "@/assets/mood/neoclassical--family-pastel-2.png";
import neoclassical_family_pastel_3 from "@/assets/mood/neoclassical--family-pastel-3.png";
import neoclassical_kids_oil_painting_1 from "@/assets/mood/neoclassical--kids-oil-painting-1.png";
import neoclassical_kids_oil_painting_2 from "@/assets/mood/neoclassical--kids-oil-painting-2.png";
import neoclassical_kids_oil_painting_3 from "@/assets/mood/neoclassical--kids-oil-painting-3.png";
import neoclassical_kids_acrylic_1 from "@/assets/mood/neoclassical--kids-acrylic-1.png";
import neoclassical_kids_acrylic_2 from "@/assets/mood/neoclassical--kids-acrylic-2.png";
import neoclassical_kids_acrylic_3 from "@/assets/mood/neoclassical--kids-acrylic-3.png";
import neoclassical_kids_pencil_sketch_1 from "@/assets/mood/neoclassical--kids-pencil-sketch-1.png";
import neoclassical_kids_pencil_sketch_2 from "@/assets/mood/neoclassical--kids-pencil-sketch-2.png";
import neoclassical_kids_pencil_sketch_3 from "@/assets/mood/neoclassical--kids-pencil-sketch-3.png";
import neoclassical_kids_watercolor_1 from "@/assets/mood/neoclassical--kids-watercolor-1.png";
import neoclassical_kids_watercolor_2 from "@/assets/mood/neoclassical--kids-watercolor-2.png";
import neoclassical_kids_watercolor_3 from "@/assets/mood/neoclassical--kids-watercolor-3.png";
import neoclassical_kids_charcoal_1 from "@/assets/mood/neoclassical--kids-charcoal-1.png";
import neoclassical_kids_charcoal_2 from "@/assets/mood/neoclassical--kids-charcoal-2.png";
import neoclassical_kids_charcoal_3 from "@/assets/mood/neoclassical--kids-charcoal-3.png";
import neoclassical_kids_pastel_1 from "@/assets/mood/neoclassical--kids-pastel-1.png";
import neoclassical_kids_pastel_2 from "@/assets/mood/neoclassical--kids-pastel-2.png";
import neoclassical_kids_pastel_3 from "@/assets/mood/neoclassical--kids-pastel-3.png";
import neoclassical_couples_oil_painting_1 from "@/assets/mood/neoclassical--couples-oil-painting-1.png";
import neoclassical_couples_oil_painting_2 from "@/assets/mood/neoclassical--couples-oil-painting-2.png";
import neoclassical_couples_oil_painting_3 from "@/assets/mood/neoclassical--couples-oil-painting-3.png";
import neoclassical_couples_acrylic_1 from "@/assets/mood/neoclassical--couples-acrylic-1.png";
import neoclassical_couples_acrylic_2 from "@/assets/mood/neoclassical--couples-acrylic-2.png";
import neoclassical_couples_acrylic_3 from "@/assets/mood/neoclassical--couples-acrylic-3.png";
import neoclassical_couples_pencil_sketch_1 from "@/assets/mood/neoclassical--couples-pencil-sketch-1.png";
import neoclassical_couples_pencil_sketch_2 from "@/assets/mood/neoclassical--couples-pencil-sketch-2.png";
import neoclassical_couples_pencil_sketch_3 from "@/assets/mood/neoclassical--couples-pencil-sketch-3.png";
import neoclassical_couples_watercolor_1 from "@/assets/mood/neoclassical--couples-watercolor-1.png";
import neoclassical_couples_watercolor_2 from "@/assets/mood/neoclassical--couples-watercolor-2.png";
import neoclassical_couples_watercolor_3 from "@/assets/mood/neoclassical--couples-watercolor-3.png";
import neoclassical_couples_charcoal_1 from "@/assets/mood/neoclassical--couples-charcoal-1.png";
import neoclassical_couples_charcoal_2 from "@/assets/mood/neoclassical--couples-charcoal-2.png";
import neoclassical_couples_charcoal_3 from "@/assets/mood/neoclassical--couples-charcoal-3.png";
import neoclassical_couples_pastel_1 from "@/assets/mood/neoclassical--couples-pastel-1.png";
import neoclassical_couples_pastel_2 from "@/assets/mood/neoclassical--couples-pastel-2.png";
import neoclassical_couples_pastel_3 from "@/assets/mood/neoclassical--couples-pastel-3.png";
import neoclassical_self_portrait_oil_painting_1 from "@/assets/mood/neoclassical--self-portrait-oil-painting-1.png";
import neoclassical_self_portrait_oil_painting_2 from "@/assets/mood/neoclassical--self-portrait-oil-painting-2.png";
import neoclassical_self_portrait_oil_painting_3 from "@/assets/mood/neoclassical--self-portrait-oil-painting-3.png";
import neoclassical_self_portrait_acrylic_1 from "@/assets/mood/neoclassical--self-portrait-acrylic-1.png";
import neoclassical_self_portrait_acrylic_2 from "@/assets/mood/neoclassical--self-portrait-acrylic-2.png";
import neoclassical_self_portrait_acrylic_3 from "@/assets/mood/neoclassical--self-portrait-acrylic-3.png";
import neoclassical_self_portrait_pencil_sketch_1 from "@/assets/mood/neoclassical--self-portrait-pencil-sketch-1.png";
import neoclassical_self_portrait_pencil_sketch_2 from "@/assets/mood/neoclassical--self-portrait-pencil-sketch-2.png";
import neoclassical_self_portrait_pencil_sketch_3 from "@/assets/mood/neoclassical--self-portrait-pencil-sketch-3.png";
import neoclassical_self_portrait_watercolor_1 from "@/assets/mood/neoclassical--self-portrait-watercolor-1.png";
import neoclassical_self_portrait_watercolor_2 from "@/assets/mood/neoclassical--self-portrait-watercolor-2.png";
import neoclassical_self_portrait_watercolor_3 from "@/assets/mood/neoclassical--self-portrait-watercolor-3.png";
import neoclassical_self_portrait_charcoal_1 from "@/assets/mood/neoclassical--self-portrait-charcoal-1.png";
import neoclassical_self_portrait_charcoal_2 from "@/assets/mood/neoclassical--self-portrait-charcoal-2.png";
import neoclassical_self_portrait_charcoal_3 from "@/assets/mood/neoclassical--self-portrait-charcoal-3.png";
import neoclassical_self_portrait_pastel_1 from "@/assets/mood/neoclassical--self-portrait-pastel-1.png";
import neoclassical_self_portrait_pastel_2 from "@/assets/mood/neoclassical--self-portrait-pastel-2.png";
import neoclassical_self_portrait_pastel_3 from "@/assets/mood/neoclassical--self-portrait-pastel-3.png";
import heritage_pets_oil_painting_1 from "@/assets/mood/heritage--pets-oil-painting-1.png";
import heritage_pets_oil_painting_2 from "@/assets/mood/heritage--pets-oil-painting-2.png";
import heritage_pets_oil_painting_3 from "@/assets/mood/heritage--pets-oil-painting-3.png";
import heritage_pets_acrylic_1 from "@/assets/mood/heritage--pets-acrylic-1.png";
import heritage_pets_acrylic_2 from "@/assets/mood/heritage--pets-acrylic-2.png";
import heritage_pets_acrylic_3 from "@/assets/mood/heritage--pets-acrylic-3.png";
import heritage_pets_pencil_sketch_1 from "@/assets/mood/heritage--pets-pencil-sketch-1.png";
import heritage_pets_pencil_sketch_2 from "@/assets/mood/heritage--pets-pencil-sketch-2.png";
import heritage_pets_pencil_sketch_3 from "@/assets/mood/heritage--pets-pencil-sketch-3.png";
import heritage_pets_watercolor_1 from "@/assets/mood/heritage--pets-watercolor-1.png";
import heritage_pets_watercolor_2 from "@/assets/mood/heritage--pets-watercolor-2.png";
import heritage_pets_watercolor_3 from "@/assets/mood/heritage--pets-watercolor-3.png";
import heritage_pets_charcoal_1 from "@/assets/mood/heritage--pets-charcoal-1.png";
import heritage_pets_charcoal_2 from "@/assets/mood/heritage--pets-charcoal-2.png";
import heritage_pets_charcoal_3 from "@/assets/mood/heritage--pets-charcoal-3.png";
import heritage_pets_pastel_1 from "@/assets/mood/heritage--pets-pastel-1.png";
import heritage_pets_pastel_2 from "@/assets/mood/heritage--pets-pastel-2.png";
import heritage_pets_pastel_3 from "@/assets/mood/heritage--pets-pastel-3.png";
import heritage_family_oil_painting_1 from "@/assets/mood/heritage--family-oil-painting-1.png";
import heritage_family_oil_painting_2 from "@/assets/mood/heritage--family-oil-painting-2.png";
import heritage_family_oil_painting_3 from "@/assets/mood/heritage--family-oil-painting-3.png";
import heritage_family_acrylic_1 from "@/assets/mood/heritage--family-acrylic-1.png";
import heritage_family_acrylic_2 from "@/assets/mood/heritage--family-acrylic-2.png";
import heritage_family_acrylic_3 from "@/assets/mood/heritage--family-acrylic-3.png";
import heritage_family_pencil_sketch_1 from "@/assets/mood/heritage--family-pencil-sketch-1.png";
import heritage_family_pencil_sketch_2 from "@/assets/mood/heritage--family-pencil-sketch-2.png";
import heritage_family_pencil_sketch_3 from "@/assets/mood/heritage--family-pencil-sketch-3.png";
import heritage_family_watercolor_1 from "@/assets/mood/heritage--family-watercolor-1.png";
import heritage_family_watercolor_2 from "@/assets/mood/heritage--family-watercolor-2.png";
import heritage_family_watercolor_3 from "@/assets/mood/heritage--family-watercolor-3.png";
import heritage_family_charcoal_1 from "@/assets/mood/heritage--family-charcoal-1.png";
import heritage_family_charcoal_2 from "@/assets/mood/heritage--family-charcoal-2.png";
import heritage_family_charcoal_3 from "@/assets/mood/heritage--family-charcoal-3.png";
import heritage_family_pastel_1 from "@/assets/mood/heritage--family-pastel-1.png";
import heritage_family_pastel_2 from "@/assets/mood/heritage--family-pastel-2.png";
import heritage_family_pastel_3 from "@/assets/mood/heritage--family-pastel-3.png";
import heritage_kids_oil_painting_1 from "@/assets/mood/heritage--kids-oil-painting-1.png";
import heritage_kids_oil_painting_2 from "@/assets/mood/heritage--kids-oil-painting-2.png";
import heritage_kids_oil_painting_3 from "@/assets/mood/heritage--kids-oil-painting-3.png";
import heritage_kids_acrylic_1 from "@/assets/mood/heritage--kids-acrylic-1.png";
import heritage_kids_acrylic_2 from "@/assets/mood/heritage--kids-acrylic-2.png";
import heritage_kids_acrylic_3 from "@/assets/mood/heritage--kids-acrylic-3.png";
import heritage_kids_pencil_sketch_1 from "@/assets/mood/heritage--kids-pencil-sketch-1.png";
import heritage_kids_pencil_sketch_2 from "@/assets/mood/heritage--kids-pencil-sketch-2.png";
import heritage_kids_pencil_sketch_3 from "@/assets/mood/heritage--kids-pencil-sketch-3.png";
import heritage_kids_watercolor_1 from "@/assets/mood/heritage--kids-watercolor-1.png";
import heritage_kids_watercolor_2 from "@/assets/mood/heritage--kids-watercolor-2.png";
import heritage_kids_watercolor_3 from "@/assets/mood/heritage--kids-watercolor-3.png";
import heritage_kids_charcoal_1 from "@/assets/mood/heritage--kids-charcoal-1.png";
import heritage_kids_charcoal_2 from "@/assets/mood/heritage--kids-charcoal-2.png";
import heritage_kids_charcoal_3 from "@/assets/mood/heritage--kids-charcoal-3.png";
import heritage_kids_pastel_1 from "@/assets/mood/heritage--kids-pastel-1.png";
import heritage_kids_pastel_2 from "@/assets/mood/heritage--kids-pastel-2.png";
import heritage_kids_pastel_3 from "@/assets/mood/heritage--kids-pastel-3.png";
import heritage_couples_oil_painting_1 from "@/assets/mood/heritage--couples-oil-painting-1.png";
import heritage_couples_oil_painting_2 from "@/assets/mood/heritage--couples-oil-painting-2.png";
import heritage_couples_oil_painting_3 from "@/assets/mood/heritage--couples-oil-painting-3.png";
import heritage_couples_acrylic_1 from "@/assets/mood/heritage--couples-acrylic-1.png";
import heritage_couples_acrylic_2 from "@/assets/mood/heritage--couples-acrylic-2.png";
import heritage_couples_acrylic_3 from "@/assets/mood/heritage--couples-acrylic-3.png";
import heritage_couples_pencil_sketch_1 from "@/assets/mood/heritage--couples-pencil-sketch-1.png";
import heritage_couples_pencil_sketch_2 from "@/assets/mood/heritage--couples-pencil-sketch-2.png";
import heritage_couples_pencil_sketch_3 from "@/assets/mood/heritage--couples-pencil-sketch-3.png";
import heritage_couples_watercolor_1 from "@/assets/mood/heritage--couples-watercolor-1.png";
import heritage_couples_watercolor_2 from "@/assets/mood/heritage--couples-watercolor-2.png";
import heritage_couples_watercolor_3 from "@/assets/mood/heritage--couples-watercolor-3.png";
import heritage_couples_charcoal_1 from "@/assets/mood/heritage--couples-charcoal-1.png";
import heritage_couples_charcoal_2 from "@/assets/mood/heritage--couples-charcoal-2.png";
import heritage_couples_charcoal_3 from "@/assets/mood/heritage--couples-charcoal-3.png";
import heritage_couples_pastel_1 from "@/assets/mood/heritage--couples-pastel-1.png";
import heritage_couples_pastel_2 from "@/assets/mood/heritage--couples-pastel-2.png";
import heritage_couples_pastel_3 from "@/assets/mood/heritage--couples-pastel-3.png";
import heritage_self_portrait_oil_painting_1 from "@/assets/mood/heritage--self-portrait-oil-painting-1.png";
import heritage_self_portrait_oil_painting_2 from "@/assets/mood/heritage--self-portrait-oil-painting-2.png";
import heritage_self_portrait_oil_painting_3 from "@/assets/mood/heritage--self-portrait-oil-painting-3.png";
import heritage_self_portrait_acrylic_1 from "@/assets/mood/heritage--self-portrait-acrylic-1.png";
import heritage_self_portrait_acrylic_2 from "@/assets/mood/heritage--self-portrait-acrylic-2.png";
import heritage_self_portrait_acrylic_3 from "@/assets/mood/heritage--self-portrait-acrylic-3.png";
import heritage_self_portrait_pencil_sketch_1 from "@/assets/mood/heritage--self-portrait-pencil-sketch-1.png";
import heritage_self_portrait_pencil_sketch_2 from "@/assets/mood/heritage--self-portrait-pencil-sketch-2.png";
import heritage_self_portrait_pencil_sketch_3 from "@/assets/mood/heritage--self-portrait-pencil-sketch-3.png";
import heritage_self_portrait_watercolor_1 from "@/assets/mood/heritage--self-portrait-watercolor-1.png";
import heritage_self_portrait_watercolor_2 from "@/assets/mood/heritage--self-portrait-watercolor-2.png";
import heritage_self_portrait_watercolor_3 from "@/assets/mood/heritage--self-portrait-watercolor-3.png";
import heritage_self_portrait_charcoal_1 from "@/assets/mood/heritage--self-portrait-charcoal-1.png";
import heritage_self_portrait_charcoal_2 from "@/assets/mood/heritage--self-portrait-charcoal-2.png";
import heritage_self_portrait_charcoal_3 from "@/assets/mood/heritage--self-portrait-charcoal-3.png";
import heritage_self_portrait_pastel_1 from "@/assets/mood/heritage--self-portrait-pastel-1.png";
import heritage_self_portrait_pastel_2 from "@/assets/mood/heritage--self-portrait-pastel-2.png";
import heritage_self_portrait_pastel_3 from "@/assets/mood/heritage--self-portrait-pastel-3.png";

export type MoodGalleryKey = "royal_noble" | "neoclassical" | "heritage";

export const moodGalleryImages: Record<MoodGalleryKey, Record<Category, Record<ArtStyle, [string, string, string]>>> = {
  "royal_noble": {
    "pets": {
      "oil-painting": [ royal_noble_pets_oil_painting_1, royal_noble_pets_oil_painting_2, royal_noble_pets_oil_painting_3 ],
      "acrylic": [ royal_noble_pets_acrylic_1, royal_noble_pets_acrylic_2, royal_noble_pets_acrylic_3 ],
      "pencil-sketch": [ royal_noble_pets_pencil_sketch_1, royal_noble_pets_pencil_sketch_2, royal_noble_pets_pencil_sketch_3 ],
      "watercolor": [ royal_noble_pets_watercolor_1, royal_noble_pets_watercolor_2, royal_noble_pets_watercolor_3 ],
      "charcoal": [ royal_noble_pets_charcoal_1, royal_noble_pets_charcoal_2, royal_noble_pets_charcoal_3 ],
      "pastel": [ royal_noble_pets_pastel_1, royal_noble_pets_pastel_2, royal_noble_pets_pastel_3 ],
    },
    "family": {
      "oil-painting": [ royal_noble_family_oil_painting_1, royal_noble_family_oil_painting_2, royal_noble_family_oil_painting_3 ],
      "acrylic": [ royal_noble_family_acrylic_1, royal_noble_family_acrylic_2, royal_noble_family_acrylic_3 ],
      "pencil-sketch": [ royal_noble_family_pencil_sketch_1, royal_noble_family_pencil_sketch_2, royal_noble_family_pencil_sketch_3 ],
      "watercolor": [ royal_noble_family_watercolor_1, royal_noble_family_watercolor_2, royal_noble_family_watercolor_3 ],
      "charcoal": [ royal_noble_family_charcoal_1, royal_noble_family_charcoal_2, royal_noble_family_charcoal_3 ],
      "pastel": [ royal_noble_family_pastel_1, royal_noble_family_pastel_2, royal_noble_family_pastel_3 ],
    },
    "kids": {
      "oil-painting": [ royal_noble_kids_oil_painting_1, royal_noble_kids_oil_painting_2, royal_noble_kids_oil_painting_3 ],
      "acrylic": [ royal_noble_kids_acrylic_1, royal_noble_kids_acrylic_2, royal_noble_kids_acrylic_3 ],
      "pencil-sketch": [ royal_noble_kids_pencil_sketch_1, royal_noble_kids_pencil_sketch_2, royal_noble_kids_pencil_sketch_3 ],
      "watercolor": [ royal_noble_kids_watercolor_1, royal_noble_kids_watercolor_2, royal_noble_kids_watercolor_3 ],
      "charcoal": [ royal_noble_kids_charcoal_1, royal_noble_kids_charcoal_2, royal_noble_kids_charcoal_3 ],
      "pastel": [ royal_noble_kids_pastel_1, royal_noble_kids_pastel_2, royal_noble_kids_pastel_3 ],
    },
    "couples": {
      "oil-painting": [ royal_noble_couples_oil_painting_1, royal_noble_couples_oil_painting_2, royal_noble_couples_oil_painting_3 ],
      "acrylic": [ royal_noble_couples_acrylic_1, royal_noble_couples_acrylic_2, royal_noble_couples_acrylic_3 ],
      "pencil-sketch": [ royal_noble_couples_pencil_sketch_1, royal_noble_couples_pencil_sketch_2, royal_noble_couples_pencil_sketch_3 ],
      "watercolor": [ royal_noble_couples_watercolor_1, royal_noble_couples_watercolor_2, royal_noble_couples_watercolor_3 ],
      "charcoal": [ royal_noble_couples_charcoal_1, royal_noble_couples_charcoal_2, royal_noble_couples_charcoal_3 ],
      "pastel": [ royal_noble_couples_pastel_1, royal_noble_couples_pastel_2, royal_noble_couples_pastel_3 ],
    },
    "self-portrait": {
      "oil-painting": [ royal_noble_self_portrait_oil_painting_1, royal_noble_self_portrait_oil_painting_2, royal_noble_self_portrait_oil_painting_3 ],
      "acrylic": [ royal_noble_self_portrait_acrylic_1, royal_noble_self_portrait_acrylic_2, royal_noble_self_portrait_acrylic_3 ],
      "pencil-sketch": [ royal_noble_self_portrait_pencil_sketch_1, royal_noble_self_portrait_pencil_sketch_2, royal_noble_self_portrait_pencil_sketch_3 ],
      "watercolor": [ royal_noble_self_portrait_watercolor_1, royal_noble_self_portrait_watercolor_2, royal_noble_self_portrait_watercolor_3 ],
      "charcoal": [ royal_noble_self_portrait_charcoal_1, royal_noble_self_portrait_charcoal_2, royal_noble_self_portrait_charcoal_3 ],
      "pastel": [ royal_noble_self_portrait_pastel_1, royal_noble_self_portrait_pastel_2, royal_noble_self_portrait_pastel_3 ],
    },
  },
  "neoclassical": {
    "pets": {
      "oil-painting": [ neoclassical_pets_oil_painting_1, neoclassical_pets_oil_painting_2, neoclassical_pets_oil_painting_3 ],
      "acrylic": [ neoclassical_pets_acrylic_1, neoclassical_pets_acrylic_2, neoclassical_pets_acrylic_3 ],
      "pencil-sketch": [ neoclassical_pets_pencil_sketch_1, neoclassical_pets_pencil_sketch_2, neoclassical_pets_pencil_sketch_3 ],
      "watercolor": [ neoclassical_pets_watercolor_1, neoclassical_pets_watercolor_2, neoclassical_pets_watercolor_3 ],
      "charcoal": [ neoclassical_pets_charcoal_1, neoclassical_pets_charcoal_2, neoclassical_pets_charcoal_3 ],
      "pastel": [ neoclassical_pets_pastel_1, neoclassical_pets_pastel_2, neoclassical_pets_pastel_3 ],
    },
    "family": {
      "oil-painting": [ neoclassical_family_oil_painting_1, neoclassical_family_oil_painting_2, neoclassical_family_oil_painting_3 ],
      "acrylic": [ neoclassical_family_acrylic_1, neoclassical_family_acrylic_2, neoclassical_family_acrylic_3 ],
      "pencil-sketch": [ neoclassical_family_pencil_sketch_1, neoclassical_family_pencil_sketch_2, neoclassical_family_pencil_sketch_3 ],
      "watercolor": [ neoclassical_family_watercolor_1, neoclassical_family_watercolor_2, neoclassical_family_watercolor_3 ],
      "charcoal": [ neoclassical_family_charcoal_1, neoclassical_family_charcoal_2, neoclassical_family_charcoal_3 ],
      "pastel": [ neoclassical_family_pastel_1, neoclassical_family_pastel_2, neoclassical_family_pastel_3 ],
    },
    "kids": {
      "oil-painting": [ neoclassical_kids_oil_painting_1, neoclassical_kids_oil_painting_2, neoclassical_kids_oil_painting_3 ],
      "acrylic": [ neoclassical_kids_acrylic_1, neoclassical_kids_acrylic_2, neoclassical_kids_acrylic_3 ],
      "pencil-sketch": [ neoclassical_kids_pencil_sketch_1, neoclassical_kids_pencil_sketch_2, neoclassical_kids_pencil_sketch_3 ],
      "watercolor": [ neoclassical_kids_watercolor_1, neoclassical_kids_watercolor_2, neoclassical_kids_watercolor_3 ],
      "charcoal": [ neoclassical_kids_charcoal_1, neoclassical_kids_charcoal_2, neoclassical_kids_charcoal_3 ],
      "pastel": [ neoclassical_kids_pastel_1, neoclassical_kids_pastel_2, neoclassical_kids_pastel_3 ],
    },
    "couples": {
      "oil-painting": [ neoclassical_couples_oil_painting_1, neoclassical_couples_oil_painting_2, neoclassical_couples_oil_painting_3 ],
      "acrylic": [ neoclassical_couples_acrylic_1, neoclassical_couples_acrylic_2, neoclassical_couples_acrylic_3 ],
      "pencil-sketch": [ neoclassical_couples_pencil_sketch_1, neoclassical_couples_pencil_sketch_2, neoclassical_couples_pencil_sketch_3 ],
      "watercolor": [ neoclassical_couples_watercolor_1, neoclassical_couples_watercolor_2, neoclassical_couples_watercolor_3 ],
      "charcoal": [ neoclassical_couples_charcoal_1, neoclassical_couples_charcoal_2, neoclassical_couples_charcoal_3 ],
      "pastel": [ neoclassical_couples_pastel_1, neoclassical_couples_pastel_2, neoclassical_couples_pastel_3 ],
    },
    "self-portrait": {
      "oil-painting": [ neoclassical_self_portrait_oil_painting_1, neoclassical_self_portrait_oil_painting_2, neoclassical_self_portrait_oil_painting_3 ],
      "acrylic": [ neoclassical_self_portrait_acrylic_1, neoclassical_self_portrait_acrylic_2, neoclassical_self_portrait_acrylic_3 ],
      "pencil-sketch": [ neoclassical_self_portrait_pencil_sketch_1, neoclassical_self_portrait_pencil_sketch_2, neoclassical_self_portrait_pencil_sketch_3 ],
      "watercolor": [ neoclassical_self_portrait_watercolor_1, neoclassical_self_portrait_watercolor_2, neoclassical_self_portrait_watercolor_3 ],
      "charcoal": [ neoclassical_self_portrait_charcoal_1, neoclassical_self_portrait_charcoal_2, neoclassical_self_portrait_charcoal_3 ],
      "pastel": [ neoclassical_self_portrait_pastel_1, neoclassical_self_portrait_pastel_2, neoclassical_self_portrait_pastel_3 ],
    },
  },
  "heritage": {
    "pets": {
      "oil-painting": [ heritage_pets_oil_painting_1, heritage_pets_oil_painting_2, heritage_pets_oil_painting_3 ],
      "acrylic": [ heritage_pets_acrylic_1, heritage_pets_acrylic_2, heritage_pets_acrylic_3 ],
      "pencil-sketch": [ heritage_pets_pencil_sketch_1, heritage_pets_pencil_sketch_2, heritage_pets_pencil_sketch_3 ],
      "watercolor": [ heritage_pets_watercolor_1, heritage_pets_watercolor_2, heritage_pets_watercolor_3 ],
      "charcoal": [ heritage_pets_charcoal_1, heritage_pets_charcoal_2, heritage_pets_charcoal_3 ],
      "pastel": [ heritage_pets_pastel_1, heritage_pets_pastel_2, heritage_pets_pastel_3 ],
    },
    "family": {
      "oil-painting": [ heritage_family_oil_painting_1, heritage_family_oil_painting_2, heritage_family_oil_painting_3 ],
      "acrylic": [ heritage_family_acrylic_1, heritage_family_acrylic_2, heritage_family_acrylic_3 ],
      "pencil-sketch": [ heritage_family_pencil_sketch_1, heritage_family_pencil_sketch_2, heritage_family_pencil_sketch_3 ],
      "watercolor": [ heritage_family_watercolor_1, heritage_family_watercolor_2, heritage_family_watercolor_3 ],
      "charcoal": [ heritage_family_charcoal_1, heritage_family_charcoal_2, heritage_family_charcoal_3 ],
      "pastel": [ heritage_family_pastel_1, heritage_family_pastel_2, heritage_family_pastel_3 ],
    },
    "kids": {
      "oil-painting": [ heritage_kids_oil_painting_1, heritage_kids_oil_painting_2, heritage_kids_oil_painting_3 ],
      "acrylic": [ heritage_kids_acrylic_1, heritage_kids_acrylic_2, heritage_kids_acrylic_3 ],
      "pencil-sketch": [ heritage_kids_pencil_sketch_1, heritage_kids_pencil_sketch_2, heritage_kids_pencil_sketch_3 ],
      "watercolor": [ heritage_kids_watercolor_1, heritage_kids_watercolor_2, heritage_kids_watercolor_3 ],
      "charcoal": [ heritage_kids_charcoal_1, heritage_kids_charcoal_2, heritage_kids_charcoal_3 ],
      "pastel": [ heritage_kids_pastel_1, heritage_kids_pastel_2, heritage_kids_pastel_3 ],
    },
    "couples": {
      "oil-painting": [ heritage_couples_oil_painting_1, heritage_couples_oil_painting_2, heritage_couples_oil_painting_3 ],
      "acrylic": [ heritage_couples_acrylic_1, heritage_couples_acrylic_2, heritage_couples_acrylic_3 ],
      "pencil-sketch": [ heritage_couples_pencil_sketch_1, heritage_couples_pencil_sketch_2, heritage_couples_pencil_sketch_3 ],
      "watercolor": [ heritage_couples_watercolor_1, heritage_couples_watercolor_2, heritage_couples_watercolor_3 ],
      "charcoal": [ heritage_couples_charcoal_1, heritage_couples_charcoal_2, heritage_couples_charcoal_3 ],
      "pastel": [ heritage_couples_pastel_1, heritage_couples_pastel_2, heritage_couples_pastel_3 ],
    },
    "self-portrait": {
      "oil-painting": [ heritage_self_portrait_oil_painting_1, heritage_self_portrait_oil_painting_2, heritage_self_portrait_oil_painting_3 ],
      "acrylic": [ heritage_self_portrait_acrylic_1, heritage_self_portrait_acrylic_2, heritage_self_portrait_acrylic_3 ],
      "pencil-sketch": [ heritage_self_portrait_pencil_sketch_1, heritage_self_portrait_pencil_sketch_2, heritage_self_portrait_pencil_sketch_3 ],
      "watercolor": [ heritage_self_portrait_watercolor_1, heritage_self_portrait_watercolor_2, heritage_self_portrait_watercolor_3 ],
      "charcoal": [ heritage_self_portrait_charcoal_1, heritage_self_portrait_charcoal_2, heritage_self_portrait_charcoal_3 ],
      "pastel": [ heritage_self_portrait_pastel_1, heritage_self_portrait_pastel_2, heritage_self_portrait_pastel_3 ],
    },
  },
};
