import type { StylePresetId } from "@/lib/style-presets";

// Auto-generated by scripts/generate-preset-thumbnails.ts

import none from "@/assets/preset_thumbnails/none.png";
import intelligent from "@/assets/preset_thumbnails/intelligent.png";
import neoclassical from "@/assets/preset_thumbnails/neoclassical.png";
import royal_noble from "@/assets/preset_thumbnails/royal_noble.png";
import heritage from "@/assets/preset_thumbnails/heritage.png";

export const STYLE_PRESET_IMAGES: Partial<Record<StylePresetId, string>> = {
  "none": none,
  "intelligent": intelligent,
  "neoclassical": neoclassical,
  "royal_noble": royal_noble,
  "heritage": heritage,
};