#!/usr/bin/env tsx
/**
 * Generates client/src/lib/mood-gallery-images.ts from assets in client/src/assets/mood/.
 * Filenames: {mood}--{category}-{medium}-{1|2|3}.png
 *
 * Run: npx tsx scripts/generate-mood-gallery-ts.ts
 */

import { readdirSync, writeFileSync } from "fs";
import { join } from "path";

const MOOD_DIR = join(process.cwd(), "client", "src", "assets", "mood");
const OUT_FILE = join(process.cwd(), "client", "src", "lib", "mood-gallery-images.ts");

const MOODS = ["royal_noble", "neoclassical", "heritage"] as const;
const CATEGORIES = ["pets", "family", "kids", "couples", "self-portrait"] as const;
const STYLES = ["oil-painting", "acrylic", "pencil-sketch", "watercolor", "charcoal", "pastel"] as const;

function toVarName(mood: string, category: string, style: string, index: number): string {
  const m = mood.replace(/-/g, "_");
  const c = category.replace(/-/g, "_");
  const s = style.replace(/-/g, "_");
  return `${m}_${c}_${s}_${index}`;
}

function main() {
  const files = readdirSync(MOOD_DIR).filter((f) => f.endsWith(".png"));
  const byKey: Record<string, Record<string, Record<string, [string, string, string]>>> = {
    royal_noble: {},
    neoclassical: {},
    heritage: {},
  };

  for (const file of files) {
    const match = file.match(/^(.+?)--(.+)-(\d+)\.png$/);
    if (!match) continue;
    const [, moodRest, rest, indexStr] = match;
    const index = parseInt(indexStr, 10);
    if (!MOODS.includes(moodRest as any) || index < 1 || index > 3) continue;

    // rest is "category-style" e.g. "pets-oil-painting" or "self-portrait-oil-painting"
    const style = STYLES.find((s) => rest.endsWith("-" + s));
    if (!style) continue;
    const category = CATEGORIES.find((c) => rest === c + "-" + style);
    if (!category) continue;

    const mood = moodRest as (typeof MOODS)[number];
    if (!byKey[mood][category]) byKey[mood][category] = {} as Record<string, [string, string, string]>;
    if (!byKey[mood][category][style]) byKey[mood][category][style] = ["", "", ""];
    const arr = byKey[mood][category][style];
    arr[index - 1] = file;
  }

  const lines: string[] = [
    `/**`,
    ` * Mood-specific gallery preview images. Auto-generated by scripts/generate-mood-gallery-ts.ts`,
    ` * Do not edit by hand.`,
    ` */`,
    `import type { Category } from "@/lib/category-context";`,
    `import type { ArtStyle } from "@shared/schema";`,
    ``,
  ];

  const varToFile: { varName: string; path: string }[] = [];
  for (const mood of MOODS) {
    for (const category of CATEGORIES) {
      for (const style of STYLES) {
        const triple = byKey[mood]?.[category]?.[style];
        if (!triple || triple.some((p) => !p)) {
          console.warn(`Missing images for ${mood} / ${category} / ${style}`);
          continue;
        }
        for (let i = 0; i < 3; i++) {
          const varName = toVarName(mood, category, style, i + 1);
          varToFile.push({ varName, path: `@/assets/mood/${triple[i]}` });
        }
      }
    }
  }

  for (const { varName, path } of varToFile) {
    lines.push(`import ${varName} from "${path}";`);
  }
  lines.push("");

  lines.push(`export type MoodGalleryKey = "royal_noble" | "neoclassical" | "heritage";`);
  lines.push("");
  lines.push(
    `export const moodGalleryImages: Record<MoodGalleryKey, Record<Category, Record<ArtStyle, [string, string, string]>>> = {`
  );

  for (const mood of MOODS) {
    lines.push(`  "${mood}": {`);
    for (const category of CATEGORIES) {
      lines.push(`    "${category}": {`);
      for (const style of STYLES) {
        const triple = byKey[mood]?.[category]?.[style];
        if (!triple || triple.some((p) => !p)) {
          lines.push(`      "${style}": [ "", "", "" ],`);
          continue;
        }
        const a = toVarName(mood, category, style, 1);
        const b = toVarName(mood, category, style, 2);
        const c = toVarName(mood, category, style, 3);
        lines.push(`      "${style}": [ ${a}, ${b}, ${c} ],`);
      }
      lines.push(`    },`);
    }
    lines.push(`  },`);
  }
  lines.push(`};`);
  lines.push("");

  writeFileSync(OUT_FILE, lines.join("\n"), "utf8");
  console.log("Wrote", OUT_FILE, "with", varToFile.length, "imports");
}

main();
